openapi: 3.0.1
info:
  title: heartbeat manager
  description: heartbeat storage service
  version: 1.1.1
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /heartbeat/expired/{heartbeatDuration}:
    parameters:
      - $ref: '#/components/parameters/heartbeatDuration'
    get:
      operationId: GetExpiredHeartbeats
      tags:
        - Heartbeat
      summary: >-
        gets ids of tasks with expired heartbeats based on the specified
        duration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/idList'
  /heartbeat/{id}:
    parameters:
      - $ref: '#/components/parameters/id'
    post:
      operationId: storeHeartbeat
      tags:
        - Heartbeat
      summary: creates or updates a heartbeat record for specified task id
      responses:
        '200':
          description: ok
  /heartbeat/remove:
    post:
      operationId: removeHeartbeatRecords
      tags:
        - Heartbeat
      summary: removes heartbeat records from db
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/idList'
      responses:
        '200':
          description: ok
components:
  parameters:
    heartbeatDuration:
      in: path
      name: heartbeatDuration
      description: specific amount of milliseconds to be considered as expired heartbeat
      required: true
      schema:
        type: integer
    id:
      in: path
      name: id
      description: task to log heartbeat for
      required: true
      schema:
        type: string
  schemas:
    idList:
      type: array
      items:
        type: string
      example:
        - id1
        - id2
