openapi: 3.0.1
info:
  title: heartbeat manager
  description: heartbeat storage service
  version: 1.4.1
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /heartbeat/expired/{heartbeatDuration}:
    parameters:
      - $ref: '#/components/parameters/heartbeatDuration'
    get:
      operationId: GetExpiredHeartbeats
      tags:
        - Heartbeat
      summary: >-
        gets ids of tasks with expired heartbeats based on the specified
        duration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/idList'
  /heartbeat/{id}:
    parameters:
      - $ref: '#/components/parameters/id'
    get:
      operationId: getHeartbeat
      tags:
        - Heartbeat
      summary: returns the heartbeat record by Id if exists
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/heartbeatRecord'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorMessage'
    post:
      operationId: storeHeartbeat
      tags:
        - Heartbeat
      summary: creates or updates a heartbeat record for specified task id
      responses:
        '200':
          description: OK
  /heartbeat/remove:
    post:
      operationId: removeHeartbeatRecords
      tags:
        - Heartbeat
      summary: removes heartbeat records from db
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/idList'
      responses:
        '200':
          description: ok
components:
  parameters:
    heartbeatDuration:
      in: path
      name: heartbeatDuration
      description: specific amount of milliseconds to be considered as expired heartbeat
      required: true
      schema:
        type: integer
    id:
      in: path
      name: id
      description: the id of the heartbeat (task)
      required: true
      schema:
        type: string
        format: uuid
  schemas:
    idList:
      type: array
      items:
        type: string
      example:
        - id1
        - id2
    heartbeatRecord:
      type: object
      properties:
        id:
          type: number
        lastHeartbeat:
          type: string
          format: date-time
    errorMessage:
      type: object
      properties:
        message:
          type: string
        stacktrace:
          type: string
      required:
        - message
