{{- $chartName := include "heartbeat-manager.name" . -}}
{{- $tracingUrl := include "heartbeat-manager.tracingUrl" . -}}
{{- $metricsUrl := include "heartbeat-manager.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  OPENAPI_FILE_PATH: {{ .Values.env.openApiFilPath | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  SERVER_PORT: {{ .Values.env.port | quote }}
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  DB_HOST: {{ .Values.env.db.host | quote }}
  DB_PORT: {{ .Values.env.db.port | quote }}
  DB_NAME: {{ .Values.env.db.database | quote }}
  DB_LOGGING: {{ .Values.env.db.logging | quote }}
  DB_SSL_ENABLE: {{ .Values.env.db.sslEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }} 
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}  
{{- end }}
