{{- $chartName := include "heartbeat-manager.name" . -}}
{{- $configmapName := include "configmap.fullname" . }}
{{- $tracingUrl := include "heartbeat-manager.tracingUrl" . -}}
{{- $metricsUrl := include "heartbeat-manager.metricsUrl" . -}}
{{- $db := (include "common.db.merged" .) | fromYaml }}

{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmapName }}
data:
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  DB_HOST: {{ $db.host | quote }}
  DB_PORT: {{ $db.port | quote }}
  DB_NAME: {{ $db.name | quote }}
  DB_SCHEMA: {{ $db.schema | quote }}
  DB_LOGGING: {{ $db.logging | quote }}
  DB_SSL_ENABLE: {{ $db.sslEnabled | quote }}
  DB_SSL_REJECT_UNAUTHORIZED: {{ $db.rejectUnauthorized | quote }}
  PGAPPNAME: {{ $chartName }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
{{- end }}
