{{- $chartName := include "heartbeat-manager.name" . -}}
{{- $tracingUrl := include "heartbeat-manager.tracingUrl" . -}}
{{- $metricsUrl := include "heartbeat-manager.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  DB_HOST: {{ .Values.sharedData.db.host | quote }}
  DB_PORT: {{ .Values.sharedData.db.port | quote }}
  DB_NAME: {{ .Values.env.db.nameOverride | default .Values.sharedData.db.name | quote }}
  DB_SCHEMA: {{ .Values.env.db.schema | quote }}
  DB_LOGGING: {{ .Values.env.db.logging | quote }}
  DB_SSL_ENABLE: {{ .Values.sharedData.db.sslEnabled | quote }}
  DB_SSL_REJECT_UNAUTHORIZED: {{ .Values.env.db.rejectUnauthorized | quote }}
  PGAPPNAME: {{ $chartName }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
{{- end }}
