global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}
  db:
    host: "localhost"
    port: 5432
    sslEnabled: false
    rejectUnauthorized: false
    secrets:
      useExternal: false
      externalSecretName: ""
enabled: true
environment: "development"
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30030 #for minikube deployment only
resetOnConfigChange: true

cloudProvider:
  dockerRegistryUrl: "my-registry-url.io"
  flavor: "openshift"
  imagePullSecretName: "my-registry-secret"

image:
  repository: "heartbeat-manager"
  tag: "latest"

local:
  certs:
    postgres:
      ca: "certs/postgres/rootCA.crt"
      key: "certs/postgres/avi.key"
      cert: "certs/postgres/avi.crt"

postgresSecret:
  enabled: true
  userName: "postgres"
  password: "postgres"

env:
  port: 80
  targetPort: 8080
  protocol: "TCP"
  openApiFilPath: "./openapi3.yaml"
  requestPayloadLimit: "1mb"
  responseCompressionEnabled: true
  logLevel: "warn"
  tracing:
    enabled: false
    url: "http://localhost:55681/v1/trace"
  metrics:
    enabled: false
    url: "http://localhost:55681/v1/metrics"      
  db:
    database: "raster"
    schema: "public"
    logging: false
    ssl: # external paths
      CA_DIR: /opt/certs/ca/
      KEY_DIR: /opt/certs/key/
      CERT_DIR: /opt/certs/cert/
      CA_FILE_LOCATION: /opt/certs/ca/ca.pem
      KEY_FILE_LOCATION: /opt/certs/key/key.pem
      CERT_FILE_LOCATION: /opt/certs/cert/cert.pem
  
resources:
  enabled: true
  value:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"

route:
  enabled: false
  path: /

ingress:
  enabled: false
  path: /
  host: "localhost"
  cors:
    enabled: true
    origin: '*'
